"""Notification intelligence.

Categories with explicit priority: Urgent > Important > Useful > Interesting >
Noise. Delivery respects a daily budget, quiet hours, urgency threshold and
digest mode — all explainable per notification ("why am I seeing this?").
"""
from __future__ import annotations

from datetime import datetime, timezone

from .util import dumps, iso, loads, uid

UTC = timezone.utc
CATEGORY_RANK = {"Urgent": 0, "Important": 1, "Useful": 2, "Interesting": 3, "Noise": 4}

class NotificationCenter:
    def __init__(self, db, events):
        self.db = db
        self.events = events

    def prefs(self) -> dict:
        row = self.db.one("SELECT value FROM preferences WHERE key='notifications.prefs'")
        defaults = {"daily_budget": 12, "quiet_hours": ["21:00", "08:00"],
                    "urgency_threshold": "Important", "digest_mode": False,
                    "channel": "in-app"}
        if row:
            defaults.update(loads(row["value"]))
        return defaults

    def set_prefs(self, patch: dict, *, actor: str = "user") -> dict:
        prefs = {**self.prefs(), **patch}
        try:
            budget = int(prefs["daily_budget"])
        except (TypeError, ValueError):
            raise ValueError("daily_budget must be an integer")
        if not 0 <= budget <= 100:
            raise ValueError("daily_budget must be between 0 and 100")
        quiet = prefs.get("quiet_hours")
        if not isinstance(quiet, list) or len(quiet) != 2 or not all(
                isinstance(value, str) and __import__("re").fullmatch(
                    r"(?:[01]\d|2[0-3]):[0-5]\d", value) for value in quiet):
            raise ValueError("quiet_hours must contain two HH:MM values")
        if prefs.get("urgency_threshold") not in CATEGORY_RANK:
            raise ValueError("urgency_threshold is invalid")
        if not isinstance(prefs.get("digest_mode"), bool):
            raise ValueError("digest_mode must be boolean")
        prefs["daily_budget"] = budget
        self.db.execute("INSERT OR REPLACE INTO preferences(key,value) VALUES(?,?)",
                        ("notifications.prefs", dumps(prefs)))
        self.events.emit("notification.policy_updated", {"keys": sorted(patch)}, actor=actor)
        return prefs

    def create(self, *, category: str, title: str, body: str | None = None,
               entity_id: str | None = None, why: str | None = None) -> dict:
        category = category if category in CATEGORY_RANK else "Useful"
        nid = uid("ntf")
        self.db.execute(
            "INSERT INTO notifications(id,category,title,body,entity_id,why,status,created_at)"
            " VALUES(?,?,?,?,?,?,'unread',?)",
            (nid, category, title, body, entity_id, why or "generated by a workflow or rule", iso()))
        self.events.emit("notification.created", {"id": nid, "category": category})
        return self.get(nid)

    def get(self, nid: str) -> dict | None:
        row = self.db.one("SELECT * FROM notifications WHERE id=?", (nid,))
        return self._map(row) if row else None

    def deliverable(self) -> dict:
        """Apply budget, quiet hours, threshold and digest policy; explain choices."""
        prefs = self.prefs()
        unread = self.list(status="unread", limit=200)
        now_hour = datetime.now(UTC).hour
        quiet_start, quiet_end = (int(h.split(":")[0]) for h in prefs["quiet_hours"])
        in_quiet = now_hour >= quiet_start or now_hour < quiet_end
        threshold_rank = CATEGORY_RANK[prefs["urgency_threshold"]]

        delivered, held = [], []
        budget = prefs["daily_budget"]
        for note in unread:
            rank = CATEGORY_RANK[note["category"]]
            reason = None
            if note["status"] != "unread":
                reason = "already handled"
            elif in_quiet and note["category"] != "Urgent":
                reason = f"quiet hours ({prefs['quiet_hours'][0]}–{prefs['quiet_hours'][1]}); only Urgent breaks through"
            elif rank > threshold_rank and prefs["digest_mode"]:
                reason = f"digest mode: {note['category']} waits for the next digest"
            elif len(delivered) >= budget:
                reason = f"daily budget of {budget} reached; deferred to protect attention"
            if reason:
                note["held_reason"] = reason
                held.append(note)
            else:
                note["delivered_reason"] = (
                    f"category {note['category']} passes threshold {prefs['urgency_threshold']} "
                    f"within budget {len(delivered) + 1}/{budget}")
                delivered.append(note)
        return {"delivered": delivered, "held": held,
                "policy": prefs, "quiet_now": in_quiet}

    def list(self, status: str | None = None, limit: int = 100) -> list[dict]:
        now = iso()
        sql = ("SELECT * FROM notifications WHERE (snoozed_until IS NULL OR snoozed_until<?)")
        args: list = [now]
        if status:
            sql += " AND status=?"; args.append(status)
        sql += " ORDER BY created_at DESC LIMIT ?"; args.append(int(limit))
        return [self._map(r) for r in self.db.query(sql, args)]

    def mark(self, nid: str, status: str, *, actor: str = "user") -> dict | None:
        if status not in {"unread", "read", "archived"}:
            raise ValueError("status must be unread, read or archived")
        cur = self.db.execute("UPDATE notifications SET status=? WHERE id=?", (status, nid))
        if not cur.rowcount:
            return None
        self.events.emit("notification.status_changed", {"id": nid, "status": status},
                         actor=actor)
        return self.get(nid)

    def snooze(self, nid: str, until_iso: str, *, actor: str = "user") -> dict | None:
        try:
            until = datetime.fromisoformat(str(until_iso).replace("Z", "+00:00"))
            if until.tzinfo is None:
                until = until.replace(tzinfo=UTC)
        except (TypeError, ValueError):
            raise ValueError("until must be a valid ISO-8601 date/time")
        cur = self.db.execute("UPDATE notifications SET snoozed_until=? WHERE id=?",
                              (until.astimezone(UTC).isoformat(timespec="seconds"), nid))
        if not cur.rowcount:
            return None
        self.events.emit("notification.snoozed", {"id": nid, "until": until.isoformat()},
                         actor=actor)
        return self.get(nid)

    @staticmethod
    def _map(row) -> dict:
        return {"id": row["id"], "category": row["category"], "title": row["title"],
                "body": row["body"], "entity_id": row["entity_id"], "why": row["why"],
                "status": row["status"], "snoozed_until": row["snoozed_until"],
                "created_at": row["created_at"]}
